### ISSUE TITLE
Add integration testing on AWS

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/integration-k8s-aws#1]
### Description
This can be done in few ways:
1. Use cloudtest as in monorepo https://github.com/networkservicemesh/networkservicemesh/tree/master/.cloudtest/aws.yaml. Estimation: `4d`
2. Use github actions doing steps from https://github.com/networkservicemesh/networkservicemesh/tree/master/.cloudtest/aws.yaml. Estimation: `5d`

**Comment by glazychev-art** [comment]
@edwarnicke 
Could you please add AWS access key?

**Comment by edwarnicke** [comment]
@glazychev-art I believe I did yesterday in environment 'EKS' :)

**Comment by denis-tingaikin** [comment]
@glazychev-art secret names:

```
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
```

**Comment by edwarnicke** [comment]
@glazychev-art How is this going?  Is there anything blocking you?

**Comment by glazychev-art** [comment]
@edwarnicke There is PR, but integration-tests failed there. The same problem as on AKS

**Comment by edwarnicke** [comment]
@artem-belov Which problem?  What do we need to solve to get unblocked?

**Comment by glazychev-art** [comment]
@edwarnicke I see that some tests don't work properly. It would be interesting to see aws-cluster logs.

**Comment by edwarnicke** [comment]
@glazychev-art Check your email, you should now have access to the aws-cluster logs :)
