### ISSUE TITLE
TestRemote_nsmgr_restart_ip is unstable on AWS

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/integration-k8s-aws#215]
## Build

https://github.com/networkservicemesh/integration-k8s-aws/pull/214/checks?check_run_id=44735425953

**Comment by glazychev-art** [comment]
https://github.com/networkservicemesh/integration-k8s-aws/actions/runs/1559436044
Logs:
[logs-300.zip](https://github.com/networkservicemesh/integration-k8s-aws/files/7690680/logs-300.zip)

**Comment by denis-tingaikin** [comment]
As I can see in logs the problem was related to registry instabillity. This can be fixed by https://github.com/networkservicemesh/sdk/pull/1213. Let's see for new incidents.

**Comment by denis-tingaikin** [comment]
Is not reproducing. Closing this for now. The issue will be reopened with a new incident.
